### ISSUE TITLE
TFA flow interference

### ISSUE THREAD

**Issue by NurbekHalikulov** [NetCal/DNC#105]
Hi everybody, 

I am a freshman and I am applying DNC to my project. I would say I have a question, not an issue.

Does TFA take into account the interference of data streams? I have different streams going through certain servers. When looking at the delay bound of foi, I would be interested to know if the interference of other streams passing through the same server has been taken into account.

Thank you

**Comment by NetCal** [comment]
Sure, it does.

Put simple, the TFA sums up the
