### ISSUE TITLE
Packetizer

### ISSUE THREAD

**Issue by NurbekHalikulov** [NetCal/DNC#106]
Hey everyone,

I am going to apply data flows based on a packet system rather than a bit-by-bit system in my implementation to receive a better worst-case analysis. As far as I understood from the script [page 41, section 7.3]( https://www.researchgate.net/publication/325442731_Network_Calculus_A_Comprehensive_Guide), we have to consider L-packetized curves. My question refers to the definition of packetized service curve and whether we can implement it in DISCO DNC toolbox. How to set up Lmax in DNC?

Could you please help me with this issue?

Kind regards, 
Nurbek

**Comment by NetCal** [comment]
Hi, the NCorg DNC does not work with stair-/step-functions at the moment see #86.

Closing this as duplicate issue.
