### ISSUE TITLE
Packetizing effect

### ISSUE THREAD

**Issue by NurbekHalikulov** [NetCal/DNC#107]
_Hello_ everyone,

As per the question placed here https://github.com/NetCal/DNC/issues/106, the NCorg DNC does not support stair-/step-functions at the moment. What if I apply the packetizing effect on R' (t) (L-packetized output) and receive continuous function instead of discrete? Hence the packetizing will weaken the service curve guarantee by one maximum packet length _l_ max/R .

If it is helpful, my question is how we define **_l_ max** for the minimum service curve of **B'** if two input arrival curves have their _l_ max_1 and _l_ max_2?

arrival_curve_1 = _l_ max_1 + rt
arrival_curve_2 = _l_ max_2  + rt

B'= B - **_l_ max** 

So _l_ max of minimum service curve of the combined system (bit-by-bit system with L-packetizer) will be the sum of _l_ max_1 and _l_ max_2 or supremum of arrival curves _l_ max?

Many thanks for your reply. 

Kind regards,
Nurbek

**Comment by NetCal** [comment]
Hi,

sure, as per NC theory, you can use a strictly larger arrival curve that has a shape conforming with the tool's restrictions.

I think the markdown formatting of GitHub broke your math (parameters, equations). It shows, e.g., "_l_ times max\textsubscript(one)" that I do not know how to interpret.

Best regards

**Comment by sbondorf** [comment]
Hi,

sure, as per NC theory, you can use a strictly larger arrival curve that has a shape conforming with the tool's restrictions.

I think the markdown formatting of GitHub broke your math (parameters, equations). It shows, e.g., "l times max\textsubscript(one)" that I do not know how to interpret.

Best regards

**Comment by NurbekHalikulov** [comment]
Hi Prof. Bondorf,

many thanks for your reply. 

I will write it here again (without formatting this time):

What if I apply the packetizing effect on R' (t) (L-packetized output) and receive continuous function instead of discrete? Hence the packetizing will weaken the service curve guarantee by one maximum packet length l(max)/R, where l(max) is the packet size.

If it would be helpful, my question is how we define l(max) for the minimum service curve of  B' if two input arrival curves have their l(max)1 and l(max)2.

arrival_curve_1 = l(max)1 + rt
arrival_curve_2 = l(max)2 + rt

B' = B - l(max)

So my question is  l(max) of the minimum service curve of the combined system (bit-by-bit system with L-packetizer) will be equal to the sum of l(max)1 and l(max)2 or supremum of l(max)s?

Many thanks for your reply.

Kind regards,
Nurbek

**Comment by NurbekHalikulov** [comment]
[NeCal.txt](https://github.com/NetCal/DNC/files/9453652/NeCal.txt)

**Comment by sbondorf** [comment]
I am not really sure I am following -- neither is this a tool issue and therefore this is not the right place to discuss. 

Having had a quick and superficial look at [Jean-Yves Le Boudec's netcalbook](https://leboudec.github.io/netcal/), Section 1.7.2, I assume you are asking how Theorem 1.7.1, statement 3, is generalized to a system with multiple L-packetized flows as input. Or, put differently, how the combined "(L1,L2)-packetizer" of two packetized flows 1 and 2 with their respective L1-packetizer and L2-packetizer looks like.

I do not have an answer for you, but the reformulation reminds me of work regarding the superposition of Arrival Processes in Deterministic Networks, in particular [this paper](https://ieeexplore.ieee.org/document/8647202). There might be more related work on this topic.
