### ISSUE TITLE
Add description for Eclipse Java 11 support

### ISSUE THREAD

**Issue by matyesz** [NetCal/DNC#57]
Eclipse does not support Java 11 at the moment although netcal compiles with it. Add descption in README.md.

**Comment by sbondorf** [comment]
I installed OpenJDK 11. Eclipse 2018-09 then shows a notification above the configuration: "You selected a JRE that this version of Eclipse JDT does not yet support fully. Some of the features may not work as expected." Therefore, I'd add to the Eclipse section of the README file:

## Java Support in Eclipse
The DiscoDNC does not use any Java 11 features that are currently unsupported by Eclipse **2018-09**. You will be prompted "You selected a JRE that this version of Eclipse JDT does not yet support fully. Some of the features may not work as expected." but the DiscoDNC runs without problems.

**Comment by matyesz** [comment]
There is a java11 compatibility plugin that can be installed, I wanted to add that to md file, as with maven it compiles in command line.

**Comment by sbondorf** [comment]
I would probably postpone adding the instructions for a compatibility workaround until we make use of Java 11 features and really require it to work. Having said that, it seems a good idea to explicitly mention the lowest Java version we require or the Java version we test our development against.

**Update (without having posted the message above first)**
I checked the Eclipse release schedule. The 2018-12 release (version 4.10) is scheduled for December 19: https://wiki.eclipse.org/Simultaneous_Release
And according to this feature article, it fully supports Java 11: https://www.eclipse.org/eclipse/news/4.10/jdt.php
Therefore, I'd recommend to just wait for another week for the incompatibility to be resolved by Eclipse's native support.

**Comment by sbondorf** [comment]
And another update: I re-opened other projects in my workspace. They have problems with Java 11 and Eclipse. Types Exception and StringBuffer are claimed to not be visible. Switching the Project to Java 10 lets these errors disappear. There is a comment that the plugin for Eclipse 2018-09 (4.9) may misbehave in the same way:
https://marketplace.eclipse.org/comment/5761#comment-5761

**Comment by matyesz** [comment]
I have not started RC2 migration yet, will try. Eclipse is somehow loosing control :(.

**Comment by NetCal** [comment]
There haven't been problems with Eclipse lately. Nonetheless, we have started to provide IntelliJ instructions, too, such that there is an alternative IDE and this issue, actually something not central to our code base, is considered closed.
