### ISSUE TITLE
compilation problem during installation

### ISSUE THREAD

**Issue by victormanoly** [NetCal/DNC#88]
Hello, 
After performing all the steps described, the project compilation gives the following error: "Missing artifact org.networkcalculus.model:NetCal-NetworkModel:jar:0.0.1-SNAPSHOT." When the project will compile it needs Num and NetworkModel (line 70 pom.xml file), but in maven repositories only Num appears, there is no NetworkModel. So I tried to install NetworkModel via https://github.com/NetCal/NetworkModel but it also gives a compilation error, the error is: "ERROR Mwe2Launcher - Problems running workflow GeneratemodelCode: java.io.IOException: The path '/NetCal-NetworkModel/model/network.genmodel' is unmapped."
Anyone with any idea to make the compilation without errors?

**Comment by matyesz** [comment]
Checking the issue. Actually the network model is not needed for core DNC functions.
To compile network model /NetCal-NetworkModel/model/network.genmodel' must be visible for mvn I am trying to reporduce the issue but at the moment stuck with maven dependencies :(.

**Comment by victormanoly** [comment]
Thanks!!
