### ISSUE TITLE
Licensing combatibility with the rtc.jar used by RTCMPA back end

### ISSUE THREAD

**Issue by mahmood1994ha** [NetCal/DNC#96]
I have a tool that performs RTC analysis which i want to contribute as an open source tool. It uses the jar provided by the [RTC-MPA toolbox](https://www.mpa.ethz.ch/Rtctoolbox/Overview) as a backend for curve representation and manipulation. I could find any information regarding the licensing status of that binary which i noticed that it's being used also by this project. 
My question is as follows: under which license does the DNC project use that jar file. 

I know that this is a question to be asked to the developers of the jar but i couldn't find any information that way. Any information from contributors to this project would be appreciated. 
Thanks.

**Comment by sbondorf** [comment]
Hi, I cannot give you any legal advise but I can briefly summarize the way we handle use of the MPA RTC toolbox jar.

The RTC MPA toolbox has a custom license, see the included ``license.txt`` file. Among other details, it states:
```
Redistribution and use in source and binary forms, with or without modi-
fication, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright 
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright 
      notice, this list of conditions and the following disclaimer in the 
      documentation and/or other materials provided with the distribution.
```

Thus, we do not bundle and/or distribute the MPA RTC toolbox ourselves. We just help our interested users to download the entire toolbox from the authors' website as this will of course retain the original copyright, license and disclaimer.

**Comment by mahmood1994ha** [comment]
Thank you for the hint. This answers my question so i'm closing this issue 🙂
