### ISSUE TITLE
Convolution_Disco_PwAffine.convolveFIFO method returning invalid ServiceCurve

### ISSUE THREAD

**Issue by davidalain** [NetCal/DNC#98]
Hi @sbondorf and @alexscheffler 

I am trying to use SFA and FIFO multiplexing but I am not able because I am facing some unexpected Exceptions during analyzes.

I have set `config.enforceMultiplexing(MultiplexingEnforcement.GLOBAL_FIFO);` before run analyzes.
In my network setup there are some servers in tandem. So at using SFA and FIFO multiplexing, then convolutions of service curves shall occur.

I have debug DNC's code and found there is an issue in `Convolution_Disco_PwAffine.convolveFIFO` method when convolving a rate-latency service curve with a zero-rate-zero-latency service curve. Which it does not occur when using ARB mux, i.e., `Convolution_Disco_PwAffine.convolveARB` method.

The following example code may help to reproduce the problem:

```
ServiceCurve service_curve_0 = Curve.getFactory().createServiceCurve("SC{(0.0,0.0),0.0;!(233.2,0.0),67.19999999999999}");
ServiceCurve service_curve_1 = Curve.getFactory().createServiceCurve("SC{(0.0,0.0),0.0}");
		
ServiceCurve result_convolveARB = Convolution_Disco_PwAffine.convolveARB(service_curve_0, service_curve_1);
System.out.println("result_convolveARB: " + result_convolveARB);
		
ServiceCurve result_convolveFIFO = Convolution_Disco_PwAffine.convolveFIFO(service_curve_0, service_curve_1);
System.out.println("result_convolveFIFO: " + result_convolveFIFO);	
```

Output for this code is:
```
result_convolveARB: SC{(0.0,0.0),0.0}
result_convolveFIFO: SC{(0.0,NaN),0.0}
```

Can you please take a look at that issue?

**Comment by davidalain** [comment]
More informations:

Due to that problem in `Convolution_Disco_PwAffine.convolveFIFO`, an exception `java.lang.IndexOutOfBoundsException` occurs during execution of 
`public Curve computeResultingCurve(Curve curve1, Curve curve2, CurveOperation operator) {...}` 
from class
`CurveUtils_Disco_PwAffine`.

Such exception is thrown at running line `543` of class `CurveUtils_Disco_PwAffine`.
The code there is 
`leftopen = curve1.getSegment(i1).isLeftopen() || curve2.getSegment(i2).isLeftopen();`.

Implementation of `computeResultingCurve` assumes all LinearSegments instances have valid values for `x`, however, sometimes `convolveFIFO` returns a curve composed of a LinearSegment with `x` equals `-Infinity` or `NaN`.
So when that happens, `i1` is incremented for a value beyond a valid index. Then an Exception `java.lang.IndexOutOfBoundsException` is thrown.

**Comment by alexscheffler** [comment]
Hi @davidalain,

since the analysis experiences a zero-rate-zero-latency service curve as a left-over service curve, this seems to indicate that your network may be overloaded, i.e., utilization > 100%. Could you check if this is the case?

**Comment by davidalain** [comment]
Hi @alexscheffler.
Thanks for your reply.

Yes.
In my network setup, some flows cross resulting zero-rate-zero-latency service curves. For that flows, the resulting end-to-end latency is Infinity. That network is not compliant for all its flows.
However, for other flows which cross non-zero service curves, the expected result for end-to-end latency should be a non-infinite value.

When I choose SFA and ABR mux, all latencies are calculated without errors. Then I get infinity e2e latencies for some flows and non-infinity for other flows.
However, these unexpected exceptions ocurr when I choose FIFO mux.
I think the problem is just to have `NaN` values in LinearSegment instances.

Could you please help me for fixing that issue of getting `NaN` values?

**Comment by davidalain** [comment]
This is one of stack traces I get:

```
java.lang.IndexOutOfBoundsException: Index out of bounds (pos=2)!
	at org.networkcalculus.dnc.curves.disco.pw_affine.Curve_Disco_PwAffine.getSegment(Curve_Disco_PwAffine.java:294)
	at org.networkcalculus.dnc.curves.disco.pw_affine.Curve_Disco_PwAffine.getSegment(Curve_Disco_PwAffine.java:1)
	at org.networkcalculus.dnc.curves.disco.pw_affine.CurveUtils_Disco_PwAffine.computeResultingCurve(CurveUtils_Disco_PwAffine.java:543)
	at org.networkcalculus.dnc.curves.disco.pw_affine.CurveUtils_Disco_PwAffine.min(CurveUtils_Disco_PwAffine.java:657)
	at org.networkcalculus.dnc.algebra.disco.pw_affine.Convolution_Disco_PwAffine.convolveFIFO(Convolution_Disco_PwAffine.java:92)
	at org.networkcalculus.dnc.algebra.disco.pw_affine.Convolution_Disco_PwAffine.convolve(Convolution_Disco_PwAffine.java:56)
	at org.networkcalculus.dnc.algebra.disco.pw_affine.Convolution_Disco_PwAffine.convolve(Convolution_Disco_PwAffine.java:257)
	at org.networkcalculus.dnc.algebra.disco.MinPlus_Disco_ConPwAffine.convolve(MinPlus_Disco_ConPwAffine.java:64)
	at org.networkcalculus.dnc.tandem.analyses.SeparateFlowAnalysis.tandemAnalysis(SeparateFlowAnalysis.java:238)
	at org.networkcalculus.dnc.tandem.analyses.SeparateFlowAnalysis.performAnalysis(SeparateFlowAnalysis.java:95)
	at org.networkcalculus.dnc.tandem.analyses.SeparateFlowAnalysis.performAnalysis(SeparateFlowAnalysis.java:82)
	at org.networkcalculus.dnc.ethernet.EthernetNetwork.performAnalysis(EthernetNetwork.java:615)
	at org.networkcalculus.dnc.ethernet.demos.Ethernet_Demo.main(Ethernet_Demo.java:67)
```


These are arguments values in that call for function `computeResultingCurve(Curve curve1, Curve curve2, CurveOperation operator) ` from class `CurveUtils_Disco_PwAffine`:
```
curve1 = SC{(-236.39999999999995,0.0),0.0;(0.0,0.0),54.39999999999998}
curve2 = SC{(0.0,0.0),0.0;!(Infinity,0.0),0.0;(NaN,0.0),292.07034764826176}
operator = MIN
```

As shown above, `curve2` is composed of following three LinearSegment values with pattern `(x,y),grad`:
```
(0.0,0.0),0.0;
!(Infinity,0.0),0.0;
(NaN,0.0),292.07034764826176
```

In some step of service curve computations, `curve2` become an invalid curve by getting a LinearSegment with `x=NaN` after another LinearSegment with `x=Infinity`.



Note: 
Package `org.networkcalculus.dnc.ethernet` is not a DNC's package. It is in an extended project created by me for providing analysis on Ethernet TSN networks using DNC.

**Comment by alexscheffler** [comment]
Hi @davidalain,

thanks for the detailed debug-output. 

It might be helpful to also have a look at the way the ARB mux handles special curves such as zero-rate-zero-latency service curves. E.g., in the convolution method it checks if one of the input curves is a zero service curve and directly returns such a curve if this is the case.

Do you think you could share your network file and write for which flow(id) you experienced these exceptions? Then we might have a closer look as well.

**Comment by davidalain** [comment]
Hi @alexscheffler .

Thanks for your reply and support for solving this issue.

The project has private data, so I cannot share some files here.
I have sent the file to you by email at your @rub.de account.

If you need any other file or data, please let me know.

**Comment by alexscheffler** [comment]
Hi @davidalain,

did your recent pull request #100 completely solve this issue?

**Comment by davidalain** [comment]
Hi @alexscheffler .

Pull Request #100 does not solve this issue.
It solves only the issue #99.

After debugging a little bit more, I found that a problem regarding this issue is an incorrect result for convolution between a piecewise-affine non-zero service curve with an affine zero service curve. Expected result is a zero curve, but I get an invalid curve.

For instance, if I take
```
service_curve_0 = SC{(0.0,0.0),0.0;!(233.2,0.0),67.19999999999999}
service_curve_1 = SC{(0.0,0.0),0.0}
```
So ``convolveFIFO(service_curve_0, service_curve_1)`` 
should return ``SC{(0.0,0.0),0.0}``,
but I get ``SC{(0.0,NaN),0.0}``.

**Comment by alexscheffler** [comment]
Hi @davidalain,

I have made some changes to the code, see #101. Now the delay bound should be infinity if the analysis encounters overloaded servers.

Could you please check the pull request?

**Comment by davidalain** [comment]
Hi @alexscheffler .
#101 solves this issue.
Thanks.
